aviatesk/JETLS.jl

- src/JETLS.jl
I tested out JETLS a bit in neovim, but neovim crashes when trying to display a range with `typemax(Int)` as the last column. This patch uses `typemax(Int32)` instead, which should still be much larger than any line length and serve the same purpose as "end of line" column. Most likely this can/should be fixed in neovim, but seemed easier to change it here for now.
> Use typemax(Int32) for last character in range

- extension.ts
This PR fixes the key name for the Julia executable path to "juliaExecutablePath" in the server initialization.
In the initialization process:
https://github.com/aviatesk/JETLS.jl/blob/e0a396b8a3d682a171fa4d3fc6df52fea8d9ad18/extension.ts#L17
Other cases:
https://github.com/aviatesk/JETLS.jl/blob/e0a396b8a3d682a171fa4d3fc6df52fea8d9ad18/package.json#L49
https://github.com/aviatesk/JETLS.jl/blob/e0a396b8a3d682a171fa4d3fc6df52fea8d9ad18/extension.ts#L71
> Fix configuration key name

- src/JETLS.jl
Currently, analysis is simply skipped if the interval between requests is less than `analysis_interval` (which is currently set to 5 seconds).  
https://github.com/aviatesk/JETLS.jl/blob/a594087aca4e8928b8fe8faa4cb7e8afee7d3c42/src/JETLS.jl#L728
However, in many cases, it is  inconvenient that fixes to errors are not reflected until the next edit.
This PR changes the behavior so that if a event arrives within a short period, analysis is delayed until the configured interval elapses instead of being skipped like [typescript-language-server](https://github.com/typescript-language-server/typescript-language-server/blob/bb1c105d30a916e92267ce411eed78cdf6ec2980/src/lsp-server.ts#L316), [python-lsp-server](https://github.com/python-lsp/python-lsp-server/blob/cc6d398befddb0c9b0f0a52affade3ca4fbfd …
> add debounce/throttle mechanism for re-analysis

- runserver.jl
- src/JETLS.jl
- src/utils.jl
Also changes `debounce` and `throttle` to take `id` object that is used to identify the callback, rather than using the function object as the key.
/cc @abap34
> fix up `throttle` implementation and use it for `reanalyze_with_context!`

- Project.toml
- README.md
So that everyone can instantiate dependency of expected versions by
running `Pkg.instantiate()`, and more importantly, to allow tests to
pass with custom versions of JET and JuliaLowering.
A drawback of this method is then we can't use packages installed in our
local package directory with simply running `pkg> dev JET JuliaLowering`.
The workaround is to temporarily comment out the `[sources]` section,
and then we can `pkg> dev JET JuliaLowering` and specify any checkout.
We'll need to use this method if we need to make changes to JET or JL
and test them against JETLS.
Another option is to use `git submodule`, but I think the solution with
`[sources]` is a bit simpler than managing `git submodule`, which is
known to be complex and tedious in general.
> enable `[sources]` section in Project.toml

- README.md
- src/completions.jl
- test/test_completions.jl
- Sort locals by distance from the cursor
- HACK: We can't expand macros through JuliaLowering yet---even if we grab the
module context, JuliaLowering needs to see the macro definition.  To fix local
completions not working when macrocalls are around the cursor, trim macrocalls
from the tree before lowering.
- Remove code attempting to find LambdaBindingInfo for completions (I was
mistakenly searching our pre-scope-resolution data structures, so the result
was always nothing).  This was just to give locals a "function" type if we can
see that they're called, so probably not worth maintaining that much code for.
- Move the `showprov` on local completions from ci.detail to ci.documentation
(after figuring out where different clients put these in the UI).
Also add a snippet to the setup …
> Small completion fixes

- Project.toml
- README.md
- runserver.jl
- src/JETLS.jl
- src/completions.jl
- test/.gitignore
- test/LocalPreferences.toml
- test/test_completions.jl
Extend the `try`/`catch` currently only enabled for completions to all
other handlers so the server won’t crash immediately during development.
In tests, disable the `try`/`catch` block to allow immediate detection
of message handler errors.
Note: Once merged, run `Pkg.instantiate()` again for installing Preferences.jl into JETLS environment.
> improve error handling and make `local_completions!` more robust

- src/completions.jl
- Changed the algorithm to mainly work on `byte_range::UnitRange{Int}` rather than checking on the first and last byte of the range.
- Some performance improvements by avoidng allocations
- Make Revise work on this file
- Avoid recursion to be able to handle possibilities of encountering huge AST
> minor refactoring on `byte_ancestors`

- src/utils.jl
- test/test_utils.jl
Prevents errors when language clients send invalid `Position` objects by adding bounds checks and early breaks. Function now gracefully handles out-of-bounds line numbers and character positions.
---
Just for reference:
I particularly found this problem occurring in the Zed editor.
In Zed, such invalid positions are passed especially when completion is triggered after deleting characters, where completion requests with valid and invalid positions seem to be sent in quick succession.
I feel like this is probably a bug on Zed's side, but I think there's no harm in making this function's implementation more robust, so I'm adding this fix.
> Add guards against invalid positions in xy_to_offset

- src/JETLS.jl
- src/completions.jl
- src/utils.jl
- test/test_completions.jl
Configure LSP completion to trigger on "@" character and implement context-aware macro name completion. When triggered by "@" or within macro name context, only show macro names with proper insertText. Otherwise, include both local and global completions as before.
Note that macro completion will not work properly for macros defined in user code like the following:
```julia
macro simplemacro(xs...)
nothing
end
@|
```
This is because when `@` is typed and the full analysis is performed, errors from undefined macro calls prevent the full analysis from properly recognizing the module context. This issue could be resolved by maintaining a separate file cache of the last successful full analysis, but that will be addressed in a separate PR.
> add macro completion support

- src/LSP/utils/interface.jl
- test/setup.jl
Add a hack to prevent omitting empty `workspaceFolders` in the serialization of `InitializeParams` during the `withserver` test roundtrips, in order to fix the `"No workspaceFolders or rootUri in InitializeRequest"` warnings appearing when `withserver` is called without `workspaceFolders` nor `rootUri` specified.
`InitializeParams` is never serialized during the usual LS lifecycle, so this hack doesn't affect any behavior of the LS for actual usecases.
> fix warnings appearing in tests

- src/completions.jl
- test/test_completions.jl
When the user explicitly triggers completion, it's possible that the program is empty. In such cases, attempts to retrieve the current node may fail, so this edge case needs to be handled properly.
> fix completion request handling for empty files

- src/JETLS.jl
- src/completions.jl
- test/test_completions.jl
- [-] Same issue when typing `\:+|`
> improve completions

- README.md
- runserver.jl
- src/JETLS.jl
- src/completions.jl
- src/diagnostics.jl
- src/registration.jl
- test/setup.jl
- test/test_completions.jl
- test/test_registration.jl
Define a new `Server` struct to make it easier to construct `ServerState` in separation for testing purposes.
It also generally improves the separation between "the internal state" of the server and "the server itself", which interacts with the external world through the endpoint.
`Server` now holds `endpoint`, `callback`, and `state::ServerState` as separate components.
Update all handlers to accept `Server` parameter and access `state` through `server.state`.
> refactor code architecture to separate `Server` and `ServerState`

- runserver.jl
- src/JETLS.jl
- test/setup.jl
- test/test_diagnostics.jl
- test/test_full_lifecycle.jl
- test/test_registration.jl
Previously, tests using `withserver` followed this pattern:
```julia
withserver() do (; in, sent_queue)
writemsg(in, ...)
out = take_with_timeout!(sent_queue)
... test with out
writemsg(in, ...)
out = take_with_timeout!(sent_queue)
... test with out
end
```
This pattern is risky because it creates implicit dependencies between test cases regarding messages in the `sent_queue`.
Therefore, I've created the following utilities to use in tests:
```julia
"""
writereadmsg(@nospecialize(msg); read::Int=1)
Write a message to the language server via JSON-RPC, read the server's received message,
and read the server's response(s).
This function also asserts that no messages remain in the queue after reading the
expected number of responses.
- `msg`: The message to send to the server
- `read::Int=1`: …
```
> test: avoid using `take_with_timeout!` in `withserver` callbacks

- .github/workflows/ci.yml
- test/test_runserver.jl
Just gave up implementing timeout for `read_lsp_message`. As `bytesavailable` seems to be very fragile.
> enable test_runserver.jl CI

- src/JETLS.jl
- src/diagnostics.jl
- src/signature-help.jl
- src/utils.jl
- test/test_signature_help.jl
- test/test_utils.jl
This is not explicitly stated in the LSP specification, but most clients seem to support URI links in the format of
`"[show text](file://path#L#C)"`,
so let's use this to make the method line information displayed in signature help jumpable.
> allow method lines appearing in signature help jumpable

- src/completions.jl
Some clients (e.g., VSCode) seem to discard completion items when filterText is not explicitly set and the beginning of the label does not match the current input.
This change explicitly sets `filterText`, and I have confirmed that it works both in VSCode and in editors where it previously worked.
> fix filtering ambiguity in LaTeX and emoji completion

- src/JETLS.jl
- src/definition.jl
- src/diagnostics.jl
- src/signature-help.jl
- test/test_diagnostics.jl
- test/test_signature_help.jl
This commit fixes poor diagnostics UX where syntax errors don't disappear immediately and JET analysis blocks real-time features like completion.
The issue was that both lightweight syntactic analysis and heavy JET-based full analysis ran on every `textDocument/didChange` notification. When full analysis took too long, it blocked subsequent request processing.
This commit separates the two analysis types:
- Syntactic analysis: Runs on `textDocument/diagnostic` requests and returns results via pull model diagnostics. This provides real-time feedback for syntax errors.
- Full analysis: Runs only on `textDocument/didSave` notifications and publishes results via `textDocument/publishDiagnostics` (push model). This prevents blocking during active editing.
This approach ensures syntactic …
> diagnostics: separate syntactic and full analysis

- src/definition.jl
- test/test_definition.jl
Go to Definition now works even when the cursor is placed just after an identifier, like:
```
func│(x)
```
If there's nothing suitable to the right of the cursor, the position just to the left (i.e., the right edge of `offset - 1`) is also checked.
> support Go to Definition at the right edge of identifiers

- src/definition.jl
- test/test_definition.jl
Properly support cases like:
```julia
let
func│
end
```
> defintion: follow up for aviatesk/JETLS.jl#77

- src/Analysis/Interpreter.jl
- src/JETLS.jl
- test/test_completions.jl
Since aviatesk/JETLS.jl#73, the full analysis is synced to `textDocument/didSave`, so the file cache used by `LSInterpreter` also needs to be synced to that notification.
With this change, even if the user continues editing after saving, as long as the last saved state is valid, the full analysis will be performed appropriately.
The downside of this approach is that `ServerState` will manage two separate file caches, which may introduce code complexity, but that's probably unavoidable.
Related to this, in the future we will also need to properly update `server.state.successfully_analyzed_file_infos` in response to `textDocument/didChange` (for more accurate definition and completion), but we'll leave that as a future task.
> LSInterpreter: sync file cache to `textDocument/didSave`

- Project.toml
Use the `aviatesk/JuliaLowering.jl#avi/JETLS` branch which combines the following JL branches:
- [`mlechu:fix-nightly`](https://github.com/c42f/JuliaLowering.jl/pull/10)
- [`aviatesk:avi/precompile`](https://github.com/c42f/JuliaLowering.jl/pull/14)
This is a temporary solution until these branches are merged into JL#master.
This enables JL precompilation and significantly improves JETLS startup time (even when JETLS `precompile_workload` is set to `false`).
> use temporary combined JL branch

- src/completions.jl
- test/test_completions.jl
`@nospecialize` is very common in our code base and ignoring it completely
makes us unable to get completions for any methods using it, since it makes method signatures completely broken.
Fortunately JL can handle it (probably because JL special-cases it), so we can just keep it and support completions for such methods.
Note that this should be a temporary fix. Ideally we want our completions to handle any methods with any macros nicely, but it'd be possible after JL comes able to expand macros.
> completion: special case `@nospecialize`

- src/completions.jl
- test/test_completions.jl
I had Claude implement the fix discussed at https://publish.obsidian.md/jetls/work/JETLS/Local+completion+performance+issue. It seems the performance issue was indeed caused by lowering on excessively large trees, and it appears to be fixed by tthis.
I'm not entirely confident that this fix is appropriate, so I would like to request a review.
> completion: fix `greatest_lowerable` to return more minimal tree

- src/analysis/full-analysis.jl
- src/analysis/resolver.jl
- src/definition.jl
- src/diagnostics.jl
- src/signature-help.jl
- src/types.jl
- src/utils/server.jl
- test/test_completions.jl
- test/test_resolver.jl
Which seems more appropriate.
Also includes a fix to `record_reverse_map!`, where it may raise exception when previously `OutOfScope` files turns out to be analyzable by some unit later.
> rename `AnalysisContext` to `AnalysisUnit`

- src/definition.jl
- test/test_definition.jl
Currently, Go to Definition fails for `+` because of:
```julia
julia> m = methods(+, (LinearAlgebra.UniformScaling, LinearAlgebra.Diagonal))[1]
+(B::UniformScaling, A::Diagonal)
@ LinearAlgebra none:0
julia> functionloc(m)
ERROR: could not determine location of method definition
Stacktrace:
[1] error(s::String)
@ Base ./error.jl:44
[2] functionloc(m::Method)
@ Base ./methodshow.jl:173
[3] top-level scope
@ REPL[30]:1
```
(https://github.com/JuliaLang/LinearAlgebra.jl/blob/c5d712277675649d79fd8921eec0b78587e7f72b/src/special.jl#L271-L273)
This change skips such methods instead of throwing them as errors. This lookup strategy will be removed in the future, but it will remain for a while, so I made a simple fix.
(I'm now using `+` as an example of a case where it fails,  but let me know if …
> definition: handle methods with unknown locations

- src/completions.jl
- test/test_completions.jl
After reconsidering the discussion at https://github.com/aviatesk/JETLS.jl/pull/103#pullrequestreview-2943628486, now I think it's better to have this completion even inside string scopes. If the completion shows up, you can just ignore it, so it'd be better than not having it available.
My previous comment was based on the fact that implementing general completion features like `global_completions!` requires tokenization, but for this specific backslash completion, I believe tokenization is not really needed.
> completion: simplify backslash completion implementation

- src/signature-help.jl
- src/utils/ast.jl
- test/test_signature_help.jl
- Fix `call1() = call2(|)`, where signature help didn't work before since it
triggered our function declaration detection
- Fix declaration detection with `where` (silly iteration bug; I wasn't testing
this properly)
- Explicitly ignore infix and postfix calls.  Before, we were assuming the first
child of the call is always the function, but this is only true for prefix
calls, so we failed to show help by chance.  I chose to ignore these mostly to
avoid adding more edge case code, but I also think it's an OK choice
taste-wise---we'll only choose to show help for `f` everywhere in
```julia
f(x + y, a:b, M')
```
Can always revisit.
- Basic support for dotcall (just treat it like a normal call)
- Make signature help work with macro calls
- `@m(a,b,c)` and `@m a b c` supported
- Hide the …
> Signature help: Macro support and other improvements

- src/utils/path.jl
- test/test_definition.jl
- test/test_utils.jl
It turned out that `to_full_path` did not handle path separator carefully. Also fixes test_definition.jl when Julia is built from source.
> path: fix `to_full_path`

- src/analysis/full-analysis.jl
- src/types.jl
- test/test_hover.jl
For allowing LSP features like hover to retrieve documentation on objects analyzed by virtual process.
> full-analysis: force concretization of `Base.Docs.doc!` calls

- src/completions.jl
- src/utils/ast.jl
- test/test_completions.jl
- test/test_utils.jl
Add `select_dotprefix_node` function to detect dot accessor contexts and resolve the target module for more accurate completion suggestions. When completing after a dot (e.g., `Base.`), completions now come from the specific module being accessed rather than the current scope.
Allows completing e.g. `JS.|` to `JS.is_identifer`, within JETLS.
> completion: support dot-prefix global completions

- src/completions.jl
- test/test_completions.jl
With this change, when `func` is undefined, it will no longer appear as a completion candidate in cases like:
```julia
│func(1.0)
```
Similarly, in Go to Definition, the `func` on the right side of the cursor will no longer be considered as a definition candidate.
ref: https://github.com/aviatesk/JETLS.jl/pull/115#issuecomment-3007784009
> exclude identifier from bindings when cursor is at its left edge

- src/definition.jl
- src/utils/ast.jl
- src/utils/binding.jl
- test/jsjl_utils.jl
- test/test_definition.jl
This change enhances the local binding jump functionality to support multiple assignment operations and enables jumps from target bindings that are positioned before the definition.
@abap34 Sorry for immediately fixing the code that was reviewed and merged. There were reasons for making the changes, so I'll explain it in inline comments. I would appreciate it if you could review it.
> definition: enhance local binding jump

- runserver.jl
Allows us to hide JETLS internal names to appear in completions, etc.
> runserver: Wrap runserver code in module with `@main` entrypoint

- README.md
- src/JETLS.jl
- src/analysis/surface-analysis.jl
- src/completions.jl
- src/diagnostics.jl
- src/precompile.jl
- src/response.jl
- src/signature-help.jl
- src/utils/ast.jl
- src/utils/binding.jl
- test/jsjl_utils.jl
- test/runtests.jl
- test/test_completions.jl
- test/test_diagnostics.jl
- test/test_surface_analysis.jl
Implements lowering-based diagnostic analysis to detect unused variable bindings. Note that this diagnostics is reported by the pull-model diagnostics, which is synced with syntactic analysis cache.
https://github.com/user-attachments/assets/caa7177a-d7f6-4f43-abe0-6eadd1e1bffd
> diagnostics: report unused bindings

- test/test_definition.jl
> test: use correct `matcher` in`with_local_definitions`

- src/definition.jl
- src/hover.jl
- src/utils/binding.jl
- test/runtests.jl
- test/test_binding.jl
- test/test_definition.jl
- test/test_hover.jl
Implement local_hover function to provide hover information for local bindings by looking up their definitions and showing their source locations in markdown format.
The information shown by this feature is essentially duplication of the "definition" feature.
In the future, we would want to show the type of this local binding, but that is only possible after the full JL integration. For now we'll just show the location of the local binding
> hover: Add local variable hover

- src/completions.jl
- src/hover.jl
- src/utils/lsp.jl
- test/test_completions.jl
- Include clickable file links in completion documentation
- Show multiple definitions in hover with separators
- Extract location text formatting into utility functions
- Remove location info from `JL.showprov` output to avoid duplication
Requires c42f/JuliaLowering.jl#16 (, which is already merged into our custom JL branch).
> Add source location links to local completions doc and hover

- test/test_completions.jl
Fix incorrect target passed from `test_single_cv` to `with_completion`.
> test: fix `test_single_cv` to use the correct target

- src/utils/general.jl
It turned out that we need these definitions until JuliaLang/julia#58916..
> fix `lsrender` to take `Markdown.[Table|LaTeX]`

- src/diagnostics.jl
- test/test_signature_help.jl
This `previousResultId` calculation is mostly meaningless, but it might help some clients accurately update these diagnostics. In particular, there seem to be cases where syntax error diagnostics remain in Zed when this field is not set.
> diagnostics: set `resultId` for the pull model diagnostics

- src/code-action.jl
- src/code-lens.jl
- src/document-synchronization.jl
- src/testrunner.jl
- src/types.jl
- test/test_testrunner.jl
This changes make the `testsetinfos` synchronization a bit more efficient and make it easier to add other code lens/actions.
> synchronize `testsetinfos` by `didChangeDocument` notification

- src/completions.jl
- src/utils/ast.jl
- src/utils/binding.jl
- src/utils/lsp.jl
- test/utils/test_ast.jl
Initialize empty result containers and add range checks before adding root nodes. Also updates `select_target_node` accordingly. I think other places where `byte_ancestors` is used handle empty anscestor list case.
> make `byte_ancestors` return empty list for out-of-range positions

- Project.toml
- src/completions.jl
- src/signature-help.jl
- src/types.jl
- src/utils/ast.jl
Main change: ParseStream no longer holds a flat token list; we need to do
something to get it.  Arguably we should do something smarter than seeking
through the tokens but I've left that for later.
TODO: preparing a commit where I try to delete the macro hack
> Bump JuliaSyntax and JuliaLowering for macro support

- src/utils/ast.jl
To make `collect(tc::TokenCursor)` etc. available, which are useful for interactive uses.
> TokenCursor: add more `iterator` interface definitions

- src/JETLS.jl
- src/inlay-hint.jl
- src/lifecycle.jl
- src/utils/server.jl
- test/runtests.jl
- test/test_inlay_hint.jl
As we begin full-scale use of JL in the future, we will make extensive use of inlay-hints for features like inline type annotations. To build the infrastructure for that purpose, I have implemented a simple `end-module` suffix inlay-hint based on syntactic analysis.
For code patterns like: 
```julia
module A
...
end
```
This automatically displays `#= module A =#` after the `end`. If there is already a comment after `end`, the inlay hint is not displayed.
> inlay-hints: show `end module` suffix

- src/analysis/surface-analysis.jl
- test/test_surface_analysis.jl
Currently we remove all macro calls due to the JL's macro compat issue, but we treat `@nospecialize` specially and keep it during lowering. However, for some reason there are cases where `JS.first_byte` becomes 0 after `@nospecialize` is applied, so we're adding that special case to surface-analysis.jl. This is expected to be resolved by aviatesk/JETLS.jl#180.
> surface-analysis: fix issues with werid `@nospecialize` expand

- src/JETLS.jl
- src/testrunner-types.jl
- src/testrunner.jl
So that we can see stacktrace from exceptions raised from tests.
> testrunner: use latest TestRunner.jl implementation

- src/analysis/surface-analysis.jl
- test/test_surface_analysis.jl
Fixes the false positive unused variable diagnostics for cases like:
```julia
struct A{T}
x::T
A(x::T; override::Union{Nothing,T}) where T = new{T}(@something override x)
end
```
> surface analysis: fix struct constructors with keyword arguments

- src/completions.jl
- src/inlay-hint.jl
- src/signature-help.jl
- src/utils/ast.jl
- test/utils/test_ast.jl
Allows `TokenCursor` to be used for `jsobj_to_range`.
> add more `TokenCursor` utilities

- src/utils/binding.jl
- test/utils/test_binding.jl
Slightly improves `__select_target_binding` implementation.
> binding: allow keyword argument binding to be selected

- src/utils/ast.jl
- src/utils/binding.jl
- test/utils/test_binding.jl
Make `select_target_binding` not select bindings from `kwcall` definitions, but return bindings from main method bodies, which are usually most interesting to us.
> binding: allow `select_target_binding` for keyword arguments

- src/document-highlight.jl
Some clients raise an error if an empty array is returned when there are no highlights (confirmed in VSCode). It appears that returning `null` is the expected response.
> use `null` instead of an empty array when no highlights are found

- src/document-synchronization.jl
- src/testrunner.jl
- src/types.jl
- src/utils/server.jl
- test/test_testrunner.jl
- test/test_types.jl
This commit adapts the testrunner infrastructure to work with the new
immutable `FileInfo` design, where `FileInfo` creates fresh
`testsetinfos` on construction rather than maintaining a mutable
vector. (xref: #229 )
Key changes to `update_testsetinfos!`:
- Now takes `prev_fi` as an explicit parameter instead of relying on
mutating the existing `FileInfo`'s `testsetinfos`
- Directly modifies `fi.testsetinfos` using `resize!` and indexed
assignment instead of `push!` operations for better
understandability
- Early return when `isnothing(prev_fi)` (initial file load) since
there are no previous test results to preserve
- Returns boolean indicating whether any diagnostics were deleted
The refactored implementation is cleaner and more intuitive:
- `prev_fi` is treated as read-only reference …
> fix testrunner integration

- src/diagnostics.jl
- test/fixtures/macros.jl
- test/fixtures/macros_JL.jl
- test/test_lowering_diagnostics.jl
When an error occurs within nested macro calls,
`JS.[first|last]_byte(err.ex)` returns the position of the innermost macro call, but this is not the outermost macro call position that `lowering_diagnostics!` expects. This problem is fixed by using `JL.flattend_provenances`.
> diagnostics: fix location info for errors of nested macro call

- src/utils/ast.jl
- test/utils/test_binding.jl
Previously, blocks within top-level scope were always shrunk, but this incorrectly excluded blocks that contained `local` statements which can introduce local bindings.
> ast: Fix scope analysis for blocks containing `local` statements

- src/analysis/full-analysis.jl
- src/document-synchronization.jl
- src/response.jl
- src/types.jl
The `staled` tracking mechanism was removed from analysis units,
simplifying the reanalysis logic and struct definition.
When the reanalysis is requested, which is hooked with the `didSave`
notification, the analysis result should be staled always under the
current implementation.
> full-analysis: Remove `staled` field from `FullAnalysisResult`

- src/types.jl
- test/utils/test_config.jl
These global configuration dictionaries are never modified during runtime and should be treated as constants. This change:
- Makes `DEFAULT_CONFIG` and `CONFIG_RELOAD_REQUIRED` `const` 
- Simplifies tests that previously modified these globals 
The constants provide the baseline configuration that should never change during the language server's lifetime. User interactions only affect the ConfigManager's watched files, not these base definitions.
> config: make DEFAULT_CONFIG and CONFIG_RELOAD_REQUIRED constants

- src/did-change-watched-files.jl
- src/lifecycle.jl
- src/types.jl
- src/utils/config.jl
- test/test_did-change-watched-files.jl
- test/utils/test_config.jl
Currently we show "restart server to take apply ..." messages on whatever configuration changes. This commit make the messages more concise and consistent based on the actual changes made by user.
We still need to update test-did-change-watched-files.jl.
> config: improve notification messages for file changes

- src/JETLS.jl
- src/formatting.jl
- src/response.jl
- src/testrunner/testrunner.jl
The testrunner and formatting features that call external processes previously used `Threads.@spawn` to perform async local execution within the previous synchronous message handling loop. Now that all message handling is performed concurrently, this is no longer necessary.
This commit removes `Threads.@spawn` from these message handlers, allowing the message handlers themselves to execute synchronously.
> remove `Threads.@spawn` from testrunner and formatting

- src/JETLS.jl
- src/analysis/Interpreter.jl
- src/analysis/full-analysis.jl
- src/document-synchronization.jl
- src/formatting.jl
- src/response.jl
- src/testrunner/testrunner.jl
- src/types.jl
Implements proper cancellation handling for operations initiated with work done progress request, including test execution, analysis, and formatting.
- Added `WorkDoneProgressCancelNotification` handling
- Pass cancel flags through progress operations
> Add cancellation support for work done progress operations

- src/utils/binding.jl
- test/utils/test_binding.jl
Skip merging occurrences for same-named bindings that don't contain static parameters to preserve correct scoping behavior.
E.g.
```julia
let xxx = rand()
if xxx > 0
let xxx = xxx
xxx += 1.0
println(xxx)
end
end
println(xxx)
end
```
> binding: Fix binding occurrence computation for local variables
