aviatesk/JETLS.jl

Project.toml
src/JETLS.jl

For using on-memory file cache.

use `include_callback` mechanism

---

src/JETLS.jl

Making it easier to integrate with JuliaLowering.

make `FileInfo` have `JuliaSyntax.ParseStream` instead of `Expr`

---

src/JETLS.jl
src/LSP/basic-json-structures.jl
src/LSP/language-features/completions.jl
src/completions.jl
src/utils.jl

For better collaborations on #19 and #20.
This PR just setups infrastructure for implementing "completions", and doesn't return anything. It will be enabled on #19 and #20.

setup basic infra for completions

---

Project.toml
src/JETLS.jl
src/completions.jl
test/fixtures/TestFullLifecycle/src/TestFullLifecycle.jl
test/test_completions.jl

Requires aviatesk/JET.jl#712.
Maybe it's time to implement JETLS's own version of `virtualprocess`..

fix the module context recognition issue

---

.gitignore
CLAUDE.md
README.md

Add a dedicated "AI-Assisted Development" section to README.md that provides guidance for developers working with AI agents. This section includes:
- Best practices for writing test code when working with them
- Instructions for using the ./julia script to specify which Julia binary should be used by them
This commit also addes the new instructions to CLAUDE.md to allow them to run test code or file autonomously.

teach AI agents to run tests

---

src/URIs2/URIs2.jl
src/URIs2/vendored_from_uris.jl
test/runtests.jl
test/test_URIs2.jl

Also fixed one typo detected by us.

added tests for URIs2

---

src/JETLS.jl
src/LSP/LSP.jl
src/LSP/basic-json-structures.jl
src/URIs2/URIs2.jl
src/URIs2/uri_helpers.jl
src/completions.jl
src/diagnostics.jl
src/utils.jl
test/setup.jl
test/test_completions.jl
test/test_diagnostics.jl
test/test_full_lifecycle.jl
test/test_signature_help.jl

Since aviatesk/JETLS.jl#52 is incomplete and seems to cause errors, I'll revert it for now.

revert automatic `URI` conversions

---

.editorconfig
.zed/settings.json

As discussed in aviatesk/JETLS.jl#61.

add .editorconfig

---

src/LSAnalysis/LSAnalyzer.jl
src/LSAnalysis/LSInterpreter.jl

adapt to JET's `ToplevelAbstractAnalyzer` interface

---

src/definition.jl
src/signature-help.jl
test/test_definition.jl

Although I found several test cases are failing (previously we actually didn't `@test` them).
@abap34 Can you look into the failures and fix them?

allow goto definition for general callables

---

src/completions.jl
src/definition.jl
src/diagnostics.jl
src/signature-help.jl
src/utils.jl
test/test_completions.jl
test/test_diagnostics.jl

Although it doesn't happen usually.

handle file cache error gracefully

---

src/LSP/base-protocol.jl
src/LSP/basic-json-structures.jl
src/LSP/specification.md

Implement `ProgressParams`, `ProgressNotification`, and work done progress
types (`WorkDoneProgressBegin`, `WorkDoneProgressReport`, `WorkDoneProgressEnd`).

LSP: add proper "progress" support

---

src/analysis/full-analysis.jl
src/definition.jl
src/signature-help.jl
src/types.jl
src/utils/path.jl
src/utils/server.jl

This is a very simple and dirty hack to make JETLS work with Base/Compiler. This will be replaced in the near future. This is just a temporary measure to resolve the immediate compiler task.

add dirty hack to support completions for Base files

---

src/completions.jl

When completion is triggered within comments (, which seems to happen on some clients like Zed), set `textEdit` to `nothing` and let the client handle positioning based on `label` rather than attempting to calculate proper text edit ranges by ourselves.

Add comment scope handling to global completions

---

src/analysis/Analyzer.jl
src/diagnostics.jl
src/utils/path.jl
test/test_LSAnalyzer.jl

Implements detection of undefined local variables. Requires JET@master and 1.12.0-rc1 for better accuracy.

diagnostics: add local undefined variable detection

---

src/completions.jl
src/definition.jl
src/signature-help.jl
src/types.jl
src/utils/server.jl
test/runtests.jl
test/test_resolver.jl
test/test_signature_help.jl

To remove `var"..."` garbages from completion documentation.

completion: post process retrived documentation

---

src/LSP/basic-json-structures.jl
src/definition.jl
test/test_definition.jl

definition: allow jump to modules

---

test/jsjl_utils.jl

I noticed some convenience functions making it into `/test`, so here are some other ones I have lying around.  If it doesn't make sense to have these here, feel free to close this PR and take them for your own startup.jl :)

Add JL utils for interactive debugging

---

src/analysis/Interpreter.jl

full-analysis: fix cross-file analysis

---

src/testrunner.jl
src/types.jl
test/test_testrunner.jl

This refactors `update_testsetinfos!` to better preserve test results when test files are modified. The key improvements are:
The implementation now tracks testset identity through the `TestsetDiagnosticsKey` which includes the testset name, allowing more accurate result preservation across file edits.

testrunner: improve test result preservation in update_testsetinfos\!

---

test/test_signature_help.jl

https://github.com/aviatesk/JET.jl/commit/c03debe7f8d1ace7017e5566e3bcc3aa04cd2363 fixed this.

fix `broken test cases

---

src/analysis/surface-analysis.jl
test/test_surface_analysis.jl

Fix up usedness information of arguments that are only used within the argument list. E.g. this is necessary to avoid reporting "unused variable diagnostics" for `a` in cases like:
```julia
hasmatch(x::RegexMatch, y::Bool=isempty(x.matches)) = y
```

surface-analysis: fix arg usage tracking for defs with default params

---

Project.toml
README.md
src/analysis/surface-analysis.jl
src/diagnostics.jl
src/testrunner.jl
src/utils/binding.jl
test/test_diagnostics.jl
test/test_surface_analysis.jl

diagnostics: report errors from JuliaLowering

---

src/JETLS.jl
src/lifecycle.jl

Monitors client processId every 60 seconds and sends a special self-shutdown token if client is no longer running, preventing orphaned server processes.

lifecycle: Add server self-shutdown mechanism when client process dies
